spring.application.name=api-gateway
server.port=9000
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/master

#Documentation
springdoc.swagger-ui.path=swagger-ui.html
#http://localhost:9000/swagger-ui.html
springdoc.api-docs.path=/api-docs
#http://localhost:9000/api-docs

springdoc.swagger-ui.urls[0].name=File Service
springdoc.swagger-ui.urls[0].url=/aggregate/file-service/v3/api-docs
springdoc.swagger-ui.urls[1].name=Article Management Service
springdoc.swagger-ui.urls[1].url=/aggregate/article-service/v3/api-docs

#Acuator Endpoint
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# resilience4j Properties
resilience4j.circuitbreaker.config.default.registerHealthIndicator=true
resilience4j.circuitbreaker.config.default.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.config.default.slidingWindowSize=10
resilience4j.circuitbreaker.config.default.failureRateThreshold=50
resilience4j.circuitbreaker.config.default.waitDurationInOpenState=30s
resilience4j.circuitbreaker.config.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.config.default.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.config.default.minimum-number-of-calls=5

# resilience4j timeout properties
resilience4j.timelimiter.config.default.timeoutDuration=30s

# resilience4j Retry Properties
resilience4j.retry.config.default.max-attempts=3
resilience4j.retry.config.default.wait-duration=30s
