spring.data.mongodb.uri=mongodb://localhost:27017/db_file
spring.application.name=file-service
server.port=8082

#Cloudinary
configuration.cloudinary.cloud-name: ${IMAGE_CLOUD_NAME}
configuration.cloudinary.cloud-api-key: ${IMAGE_CLOUD_API_KEY}
configuration.cloudinary.cloud-api-secret: ${IMAGE_CLOUD_API_SECRET}
